// Mem-Lexis 词根词缀数据库
// 包含前缀(Prefix)、词根(Root)、后缀(Suffix)

const WORD_ROOTS = {
  // ==================== 前缀 Prefix ====================
  // 否定/相反
  un: { type: 'prefix', meaning: '不/非', words: ['unhappy', 'undo', 'unclear', 'unknown', 'unusual'] },
  in: { type: 'prefix', meaning: '不/内', words: ['inactive', 'incorrect', 'informal', 'invisible', 'indoor'] },
  im: { type: 'prefix', meaning: '不/内', words: ['impossible', 'immoral', 'impolite', 'imperfect', 'immature'] },
  dis: { type: 'prefix', meaning: '不/相反', words: ['disappear', 'disagree', 'disconnect', 'dislike', 'disorder'] },
  non: { type: 'prefix', meaning: '非/不', words: ['nonsense', 'nonstop', 'nonviolent', 'nonsense', 'nonexistent'] },
  mis: { type: 'prefix', meaning: '错误', words: ['mistake', 'misunderstand', 'mislead', 'misfortune', 'misbehave'] },
  anti: { type: 'prefix', meaning: '反对', words: ['antibiotic', 'antifreeze', 'anti-war', 'antioxidant', 'antibody'] },
  de: { type: 'prefix', meaning: '向下/否定', words: ['decrease', 'decode', 'defrost', 'devalue', 'degrade'] },
  counter: { type: 'prefix', meaning: '相反', words: ['counterattack', 'counterpart', 'counteract', 'counterclockwise'] },

  // 方向/位置
  pre: { type: 'prefix', meaning: '前/预先', words: ['preview', 'predict', 'preheat', 'prepare', 'prefix', 'precaution'] },
  post: { type: 'prefix', meaning: '后', words: ['postpone', 'postwar', 'postgraduate', 'postcard', 'postscript'] },
  pro: { type: 'prefix', meaning: '向前/支持', words: ['progress', 'project', 'promote', 'proclaim', 'prolong'] },
  re: { type: 'prefix', meaning: '再/回', words: ['restart', 'review', 'return', 'repeat', 'react', 'rewrite', 'rebuild'] },
  retro: { type: 'prefix', meaning: '向后', words: ['retrograde', 'retrospect', 'retroactive', 'retrospective'] },
  fore: { type: 'prefix', meaning: '前', words: ['forecast', 'foresee', 'forehead', 'foreground', 'foremost'] },
  inter: { type: 'prefix', meaning: '之间', words: ['international', 'internet', 'interview', 'interact', 'intermediate'] },
  trans: { type: 'prefix', meaning: '跨越', words: ['translate', 'transport', 'transform', 'transplant', 'transparent'] },
  sub: { type: 'prefix', meaning: '下', words: ['subway', 'submarine', 'subtotal', 'substandard', 'subdivide'] },
  super: { type: 'prefix', meaning: '超级/上', words: ['supermarket', 'supernatural', 'superstar', 'superpower', 'supersonic'] },
  over: { type: 'prefix', meaning: '过度/上方', words: ['overeat', 'overlook', 'oversea', 'overcome', 'overestimate'] },
  under: { type: 'prefix', meaning: '下方', words: ['underground', 'underline', 'underestimate', 'undergo', 'undertake'] },
  up: { type: 'prefix', meaning: '向上', words: ['uplift', 'upgrade', 'uphill', 'update', 'uphold'] },
  down: { type: 'prefix', meaning: '向下', words: ['downtown', 'download', 'downgrade', 'downcast', 'downfall'] },
  out: { type: 'prefix', meaning: '外/超过', words: ['outdoor', 'outline', 'outbreak', 'outrage', 'outperform'] },
  ex: { type: 'prefix', meaning: '外/前任', words: ['export', 'exit', 'exclude', 'ex-wife', 'ex-president'] },
  e: { type: 'prefix', meaning: '外/出', words: ['emit', 'evade', 'erupt', 'evaluate', 'eliminate'] },
  ec: { type: 'prefix', meaning: '外/环境', words: ['ecology', 'economy', 'ecosystem', 'ecstasy', 'eclipse'] },
  ob: { type: 'prefix', meaning: '对面/反对', words: ['object', 'obtain', 'obvious', 'occupy', 'obstacle'] },
  op: { type: 'prefix', meaning: '对向', words: ['oppose', 'opponent', 'opportunity', 'oppress', 'option'] },
  op: { type: 'prefix', meaning: '相反', words: ['opposite', 'opposition', 'optical', 'optimistic'] },

  // 数量/程度
  uni: { type: 'prefix', meaning: '一', words: ['uniform', 'universe', 'unicorn', 'unify', 'union'] },
  bi: { type: 'prefix', meaning: '二', words: ['bicycle', 'bilingual', 'bisecond', 'binocular', 'bipolar'] },
  tri: { type: 'prefix', meaning: '三', words: ['triangle', 'tricycle', 'triple', 'tripod', 'trinity'] },
  multi: { type: 'prefix', meaning: '多', words: ['multiply', 'multimedia', 'multinational', 'multiple', 'multitude'] },
  poly: { type: 'prefix', meaning: '多', words: ['polytechnic', 'polyglot', 'polygon', 'polyester', 'polynomial'] },
  semi: { type: 'prefix', meaning: '半', words: ['semicircle', 'semifinal', 'semiconductor', 'semicolon', 'semi-transparent'] },
  hemi: { type: 'prefix', meaning: '半', words: ['hemisphere', 'hemicycle', 'hemihydrate'] },
  demi: { type: 'prefix', meaning: '半', words: ['demigod', 'demilune', 'demi-fixed'] },
  holo: { type: 'prefix', meaning: '全', words: ['hologram', 'holistic', 'holocene', 'holomorphic'] },
  pan: { type: 'prefix', meaning: '全/泛', words: ['pandemic', 'panorama', 'pan-American', 'panslavism'] },
  omni: { type: 'prefix', meaning: '全', words: ['omnipresent', 'omnipotent', 'omniscient', 'omnibus', 'omnivorous'] },
  macro: { type: 'prefix', meaning: '大/宏观', words: ['macrocosm', 'macro-economics', 'macroeconomic', 'macrostructure'] },
  micro: { type: 'prefix', meaning: '小/微观', words: ['microscope', 'microwave', 'microphone', 'microbiology', 'microchip'] },
  mega: { type: 'prefix', meaning: '巨大', words: ['megabyte', 'megaphone', 'megalopolis', 'mega-star', 'mega-rich'] },
  mini: { type: 'prefix', meaning: '小', words: ['minibus', 'miniskirt', 'minimize', 'miniature', 'mini-computer'] },
  auto: { type: 'prefix', meaning: '自动', words: ['automobile', 'automatic', 'autopilot', 'autobiography', 'autonomy'] },
  hyper: { type: 'prefix', meaning: '过度', words: ['hyperactive', 'hypertext', 'hypertension', 'hyperbole', 'hypermarket'] },
  super: { type: 'prefix', meaning: '超级', words: ['supernatural', 'superstar', 'superhighway', 'supersonic', 'superlative'] },
  ultra: { type: 'prefix', meaning: '极端', words: ['ultramodern', 'ultrasonic', 'ultra-violet', 'ultra-conservative'] },
  extra: { type: 'prefix', meaning: '额外', words: ['extraordinary', 'extracurricular', 'extraversion', 'extra-terrestrial'] },
  inter: { type: 'prefix', meaning: '之间', words: ['interfere', 'interior', 'internal', 'interpret', 'interrupt'] },
  intra: { type: 'prefix', meaning: '内部', words: ['intranet', 'intravenous', 'intracity', 'intramural'] },
  infra: { type: 'prefix', meaning: '下方', words: ['infrastructure', 'infrared', 'infrahuman', 'infrasonic'] },
  circum: { type: 'prefix', meaning: '周围', words: ['circumference', 'circumnavigate', 'circumstance', 'circular'] },
  co: { type: 'prefix', meaning: '共同', words: ['cooperate', 'coordinate', 'coexist', 'co-founder', 'coincide'] },
  col: { type: 'prefix', meaning: '共同', words: ['collaborate', 'collect', 'college', 'colleague', 'collide'] },
  com: { type: 'prefix', meaning: '共同', words: ['combine', 'comfort', 'command', 'communicate', 'community'] },
  con: { type: 'prefix', meaning: '共同', words: ['connect', 'contain', 'continue', 'contrast', 'convenient'] },
  cor: { type: 'prefix', meaning: '共同', words: ['correspond', 'correct', 'corrupt', 'correlate', 'corrode'] },
  sym: { type: 'prefix', meaning: '共同', words: ['symbol', 'sympathy', 'symmetry', 'symptom', 'symphony'] },
  syn: { type: 'prefix', meaning: '共同', words: ['synchronize', 'synonym', 'synthesis', 'syndrome', 'synopsis'] },

  // 时间
  chron: { type: 'prefix', meaning: '时间', words: ['chronology', 'chronic', 'chronicle', 'chronometer', 'synchronize'] },
  neo: { type: 'prefix', meaning: '新', words: ['neoclassic', 'neonatal', 'neo-colonialism', 'neologism'] },
  paleo: { type: 'prefix', meaning: '古老', words: ['paleontology', 'paleozoic', 'paleography', 'paleoclimate'] },
  arche: { type: 'prefix', meaning: '古老', words: ['archaeology', 'archaic', 'archaeologist', 'archaeological'] },
  prist: { type: 'prefix', meaning: '原始', words: ['pristine', 'priapism'] },

  // 空间/维度
  centri: { type: 'prefix', meaning: '中心', words: ['centrifugal', 'centripetal', 'centrobaric'] },
  cent: { type: 'prefix', meaning: '百', words: ['century', 'centimeter', 'centennial', 'centipede', 'percent'] },
  milli: { type: 'prefix', meaning: '千分之一', words: ['millimeter', 'milligram', 'millennial', 'millennium'] },
  kilo: { type: 'prefix', meaning: '千', words: ['kilometer', 'kilogram', 'kilowatt', 'kilocalorie'] },
  deci: { type: 'prefix', meaning: '十分之一', words: ['decimeter', 'decigram', 'decimal', 'decimate'] },
  dec: { type: 'prefix', meaning: '十', words: ['decade', 'December', 'decimal', 'decathlon'] },
  oct: { type: 'prefix', meaning: '八', words: ['October', 'octagon', 'octopus', 'octave', 'octet'] },
  quadr: { type: 'prefix', meaning: '四', words: ['quadrangle', 'quadrant', 'quadrilateral', 'quadrennial'] },
  pent: { type: 'prefix', meaning: '五', words: ['pentagon', 'pentagram', 'pentathlon', 'pentoxide'] },
  hex: { type: 'prefix', meaning: '六', words: ['hexagon', 'hexagram', 'hexadecimal', 'hexapod'] },
  sept: { type: 'prefix', meaning: '七', words: ['September', 'septuple', 'septcentennial'] },
  non: { type: 'prefix', meaning: '九', words: ['nonagon', 'nonuple', 'nonagenarian'] },
  dec: { type: 'prefix', meaning: '十', words: ['decimate', 'decimation'] },

  // 移动/变化
  af: { type: 'prefix', meaning: '向/加强', words: ['affirm', 'affect', 'afraid', 'afford', 'advance'] },
  ef: { type: 'prefix', meaning: '出/向外', words: ['effect', 'effort', 'eject', 'elect', 'emit'] },
  am: { type: 'prefix', meaning: '周围', words: ['amble', 'ambient', 'ambition', 'ambiguous', 'ambulance'] },
  ambi: { type: 'prefix', meaning: '双', words: ['ambiguous', 'ambition', 'ambient', 'ambivalent', 'bilateral'] },
  amphi: { type: 'prefix', meaning: '双', words: ['amphibian', 'amphitheater', 'amphibious'] },
  ana: { type: 'prefix', meaning: '向上/再', words: ['analyze', 'anatomy', 'analog', 'anachronism', 'anagram'] },
  apo: { type: 'prefix', meaning: '远离', words: ['apology', 'apology', 'apostle', 'apology', 'apogee'] },
  apo: { type: 'prefix', meaning: '分开', words: ['apology', 'apocrypha', 'apostasy', 'apocalypse'] },
  cat: { type: 'prefix', meaning: '向下', words: ['catalog', 'catastrophe', 'catapult', 'cataract', 'cathode'] },
  dia: { type: 'prefix', meaning: '穿过', words: ['dialogue', 'diameter', 'diagnose', 'dialect', 'diagonal'] },
  per: { type: 'prefix', meaning: '通过/完全', words: ['perfect', 'perform', 'permit', 'persist', 'pervade'] },
  peri: { type: 'prefix', meaning: '周围', words: ['period', 'perimeter', 'peripheral', 'periscope', 'pericardium'] },
  meta: { type: 'prefix', meaning: '之后/变化', words: ['metaphor', 'metaphysics', 'metabolism', 'metadata', 'metacognition'] },
  para: { type: 'prefix', meaning: '旁边/保护', words: ['paragraph', 'parallel', 'paradigm', 'parasite', 'parachute'] },
  cir: { type: 'prefix', meaning: '圆/环', words: ['circle', 'circuit', 'circular', 'circumference', 'circulate'] },

  // 状态/性质
  a: { type: 'prefix', meaning: '不/无', words: ['atypical', 'asexual', 'amoral', 'anonymous', 'achromatic'] },
  an: { type: 'prefix', meaning: '不/无', words: ['anarchism', 'anecdote', 'anemia', 'anomaly', 'anesthetic'] },
  eu: { type: 'prefix', meaning: '好/优', words: ['euphoria', 'eugenics', 'euphony', 'eupepsia', 'euthanasia'] },
  dys: { type: 'prefix', meaning: '坏/困难', words: ['dysfunction', 'dyslexia', 'dystopia', 'dyspepsia', 'dysentery'] },
  eu: { type: 'prefix', meaning: '真/好', words: ['eulogy', 'euphemism', 'euphoria', 'evangel'] },
  magn: { type: 'prefix', meaning: '大', words: ['magnify', 'magnificent', 'magnitude', 'magnate', 'magnolia'] },
  mega: { type: 'prefix', meaning: '大', words: ['megaloman', 'megaphone', 'melancholy'] },
  plen: { type: 'prefix', meaning: '满', words: ['plenty', 'plenary', 'plenipotentiary', 'plenum'] },
  neo: { type: 'prefix', meaning: '新', words: ['neoclassic', 'neon', 'neophyte', 'neoplasm'] },
  ortho: { type: 'prefix', meaning: '正/直', words: ['orthodox', 'orthopedic', 'orthography', 'orthogonal'] },
  ortho: { type: 'prefix', meaning: '正确', words: ['orthodoxy', 'orthodontist', 'orthomolecular'] },
  philo: { type: 'prefix', meaning: '爱', words: ['philosophy', 'philanthropy', 'philology', 'philosopher'] },
  phil: { type: 'prefix', meaning: '爱', words: ['philanthropist', 'philosophile', 'philharmonic'] },
  poly: { type: 'prefix', meaning: '多', words: ['polyglot', 'polygamy', 'polytechnic', 'polygon'] },
  proto: { type: 'prefix', meaning: '原始', words: ['protocol', 'prototype', 'protoplasm', 'protozoa'] },
  pseudo: { type: 'prefix', meaning: '伪', words: ['pseudonym', 'pseudo-science', 'pseudonym', 'pseudopod'] },
  aqu: { type: 'prefix', meaning: '水', words: ['aquarium', 'aquatic', 'aqueduct', 'aquifer', 'aqualung'] },
  aqua: { type: 'prefix', meaning: '水', words: ['aquarium', 'aquatic', 'aqua regia'] },
  geo: { type: 'prefix', meaning: '地球', words: ['geography', 'geology', 'geometry', 'geophysics', 'geothermal'] },
  aero: { type: 'prefix', meaning: '空气', words: ['aerospace', 'aerodrome', 'aeronautics', 'aerosol', 'aerobics'] },
  aero: { type: 'prefix', meaning: '航空', words: ['aerodrome', 'aeronautics', 'aerospace', 'aerostat'] },
  thermo: { type: 'prefix', meaning: '热', words: ['thermometer', 'thermodynamics', 'thermocline', 'thermos', 'thermophilic'] },
  electro: { type: 'prefix', meaning: '电', words: ['electrical', 'electricity', 'electronic', 'electrode', 'electrolyte'] },
  bio: { type: 'prefix', meaning: '生命', words: ['biology', 'biography', 'biotech', 'biodegradable', 'biochemistry'] },
  vita: { type: 'prefix', meaning: '生命', words: ['vitamin', 'vital', 'vitality', 'vitalize', 'revitalize'] },
  zoo: { type: 'prefix', meaning: '动物', words: ['zoology', 'zoonosis', 'zoophyte', 'zoomorphism'] },
  phyto: { type: 'prefix', meaning: '植物', words: ['phytoplankton', 'phytochemical', 'phytotherapy', 'phytotomy'] },

  // ==================== 词根 Root ====================
  // 生命/身体
  bio: { type: 'root', meaning: '生命', words: ['biology', 'biography', 'biotech', 'antibiotic', 'symbiosis'] },
  vita: { type: 'root', meaning: '生命', words: ['vitamin', 'vital', 'vitality', 'revitalize', 'vitaminic'] },
  gen: { type: 'root', meaning: '出生/产生', words: ['generate', 'generation', 'genetic', 'genius', 'gentle'] },
  nat: { type: 'root', meaning: '出生', words: ['native', 'natural', 'nature', 'prenatal', 'neonate'] },
  viv: { type: 'root', meaning: '活', words: ['vivid', 'survive', 'vital', 'revive', 'viva'] },
  vivi: { type: 'root', meaning: '活', words: ['vivify', 'viviparous', 'vivisection'] },
  mort: { type: 'root', meaning: '死', words: ['mortal', 'mortality', 'mortgage', 'morbid', 'immortal'] },
  corp: { type: 'root', meaning: '身体', words: ['corporal', 'corporate', 'corpse', 'corpus', 'corporeal'] },
  corpor: { type: 'root', meaning: '身体', words: ['corporation', 'corporate', 'corpus'] },
  anim: { type: 'root', meaning: '生命/精神', words: ['animal', 'animate', 'equanimity', 'longanimity', 'animation'] },
  alma: { type: 'root', meaning: '灵魂', words: ['alma mater', 'exanimate', 'reanimate'] },
  psyc: { type: 'root', meaning: '心理', words: ['psychology', 'psyche', 'psychic', 'psychoanalysis', 'psychosis'] },
  somn: { type: 'root', meaning: '睡眠', words: ['insomnia', 'somnolent', 'somnambulism', 'hypnos', 'hypnosis'] },
  dorm: { type: 'root', meaning: '睡眠', words: ['dormitory', 'dormant', 'dormancy', 'dormitive'] },
  ped: { type: 'root', meaning: '脚', words: ['pedestrian', 'pedal', 'expedition', 'impede', 'pedestrian'] },
  pod: { type: 'root', meaning: '脚', words: ['podiatrist', 'podium', 'podocarp', 'tripod', 'centipede'] },
  man: { type: 'root', meaning: '手', words: ['manual', 'manufacture', 'manuscript', 'manage', 'emancipate'] },
  manu: { type: 'root', meaning: '手', words: ['manual', 'manuscript', 'manufacture', 'manumit'] },
  cap: { type: 'root', meaning: '头', words: ['capital', 'captain', 'capitulate', 'decapitate', 'capitation'] },
  cip: { type: 'root', meaning: '拿', words: ['participate', 'principal', 'principle', 'recipient', 'precipice'] },
  cept: { type: 'root', meaning: '拿', words: ['except', 'accept', 'concept', 'receptacle', 'intercept'] },
  dent: { type: 'root', meaning: '牙齿', words: ['dental', 'dentist', 'indent', 'trident', 'edentulous'] },
  ocul: { type: 'root', meaning: '眼睛', words: ['ocular', 'oculist', 'binocular', 'monocular', 'oculomotor'] },
  opt: { type: 'root', meaning: '眼睛/选择', words: ['optical', 'optics', 'option', 'adopt', 'optimist'] },
  audi: { type: 'root', meaning: '听', words: ['audio', 'audience', 'auditory', 'inaudible', 'auditorium'] },
  aud: { type: 'root', meaning: '听', words: ['audit', 'auditor', 'audible', 'audience'] },
  phon: { type: 'root', meaning: '声音', words: ['phonetics', 'phonics', 'telephone', 'symphony', 'microphone'] },
  pho: { type: 'root', meaning: '声音', words: ['phone', 'phonograph', 'phoneme', 'phonology'] },
  voc: { type: 'root', meaning: '声音/呼叫', words: ['vocal', 'vocabulary', 'advocate', 'convoke', 'provoke'] },
  vag: { type: 'root', meaning: '行走/游荡', words: ['vagrant', 'vagabond', 'vagary', 'vague', 'divagate'] },
  val: { type: 'root', meaning: '价值/强', words: ['value', 'valid', 'valuate', 'equivalent', 'valiant'] },
  valu: { type: 'root', meaning: '价值', words: ['value', 'evaluate', 'undervalue', 'valuable'] },
  fort: { type: 'root', meaning: '强', words: ['fort', 'fortress', 'fortify', 'fortitude', 'effort'] },
  force: { type: 'root', meaning: '力量', words: ['force', 'forceful', 'reinforce', 'enforce', 'forceful'] },
  strain: { type: 'root', meaning: '拉紧', words: ['strain', 'restrain', 'constrain', 'strait', 'stress'] },
  strict: { type: 'root', meaning: '拉紧', words: ['strict', 'restrict', 'constrict', 'district', 'strike'] },
  tend: { type: 'root', meaning: '伸展', words: ['tend', 'tender', 'tenderness', 'extend', 'intend'] },
  tens: { type: 'root', meaning: '伸展', words: ['tension', 'intense', 'extensive', 'tensor', 'ostensible'] },
  tract: { type: 'root', meaning: '拉', words: ['tractor', 'attract', 'contract', 'extract', 'distract'] },
  tractions: { type: 'root', meaning: '拉', words: ['attraction', 'extraction', 'contraction', 'distraction', 'protraction'] },
  press: { type: 'root', meaning: '压', words: ['press', 'pressure', 'compress', 'depress', 'impress'] },
  prim: { type: 'root', meaning: '第一', words: ['primary', 'prime', 'primitive', 'primo', 'primate'] },
  prin: { type: 'root', meaning: '第一', words: ['prince', 'principal', 'principle', 'pristine'] },
  sec: { type: 'root', meaning: '跟随', words: ['second', 'secular', 'consecutive', 'execute', 'persecute'] },
  sequ: { type: 'root', meaning: '跟随', words: ['sequence', 'subsequent', 'consequence', 'sequel', 'sequencer'] },
  cur: { type: 'root', meaning: '跑', words: ['current', 'currency', 'cursor', 'occur', 'recur'] },
  cours: { type: 'root', meaning: '跑', words: ['course', 'discourse', 'intercourse', 'recourse', 'concourse'] },
  ced: { type: 'root', meaning: '走', words: ['precede', 'proceed', 'recede', 'concede', 'exceed'] },
  cess: { type: 'root', meaning: '走', words: ['process', 'success', 'access', 'recess', 'ancestor'] },
  grad: { type: 'root', meaning: '走/步', words: ['gradual', 'graduate', 'grade', 'degrade', 'gradual'] },
  gress: { type: 'root', meaning: '走', words: ['progress', 'aggress', 'congress', 'transgress', 'digress'] },
  vey: { type: 'root', meaning: '路', words: ['convey', 'survey', 'envoy', 'voyage', 'via'] },
  vi: { type: 'root', meaning: '路', words: ['via', 'viable', 'trivial', 'deviate', 'obvious'] },
  via: { type: 'root', meaning: '路', words: ['viaduct', 'viaticum', 'trivial', 'deviate'] },
  voc: { type: 'root', meaning: '声音', words: ['vocal', 'vociferate', 'vocabulary', 'advocate', 'invoke'] },
  loqu: { type: 'root', meaning: '说', words: ['eloquent', 'colloquial', 'soliloquy', 'loquacious', 'elocution'] },
  loc: { type: 'root', meaning: '说', words: ['allocate', 'local', 'location', 'dislocate', 'collocate'] },
  liter: { type: 'root', meaning: '文字', words: ['literal', 'literacy', 'literature', 'alliterate', 'obliterate'] },
  graph: { type: 'root', meaning: '写/画', words: ['graphic', 'biography', 'photograph', 'telegraph', 'autograph'] },
  gram: { type: 'root', meaning: '写/画', words: ['grammar', 'epigram', 'program', 'cryptogram', 'diagram'] },
  scrib: { type: 'root', meaning: '写', words: ['scribe', 'describe', 'prescribe', 'subscribe', 'inscribe'] },
  script: { type: 'root', meaning: '写', words: ['script', 'transcript', 'manuscript', 'conscript', 'postscript'] },
  mit: { type: 'root', meaning: '发送', words: ['emit', 'transmit', 'submit', 'permit', 'admit'] },
  miss: { type: 'root', meaning: '发送', words: ['missile', 'mission', 'dismiss', 'promise', 'compromise'] },
  port: { type: 'root', meaning: '携带', words: ['portable', 'import', 'export', 'transport', 'report'] },
  lat: { type: 'root', meaning: '携带', words: ['translate', 'translate', 'relate', 'correlate', 'superlative'] },
  fer: { type: 'root', meaning: '携带/产生', words: ['transfer', 'refer', 'differ', 'prefer', 'suffer'] },
  fer: { type: 'root', meaning: '带来', words: ['confer', 'offer', 'prefer', 'refer', 'suffer'] },
  late: { type: 'root', meaning: '带来', words: ['translate', 'collater', 'oblate', 'ablate'] },
  duc: { type: 'root', meaning: '引导', words: ['conduct', 'educate', 'induce', 'reduce', 'produce'] },
  duct: { type: 'root', meaning: '引导', words: ['duct', 'abduct', 'conduct', 'induct', 'seduce'] },
  ject: { type: 'root', meaning: '抛', words: ['inject', 'project', 'reject', 'eject', 'subject'] },
  pel: { type: 'root', meaning: '推', words: ['propel', 'expel', 'repel', 'compel', 'dispel'] },
  puls: { type: 'root', meaning: '推', words: ['pulse', 'pulsar', 'expel', 'propel', 'compel'] },
  pel: { type: 'root', meaning: '推', words: ['propeller', 'expel', 'impel', 'compel', 'dispel'] },
  pend: { type: 'root', meaning: '悬挂/花费', words: ['suspend', 'pending', 'expend', 'spend', 'depend'] },
  pens: { type: 'root', meaning: '悬挂/花费', words: ['pension', 'compensate', 'dispense', 'suspense', 'expense'] },
  preci: { type: 'root', meaning: '价值', words: ['precious', 'appreciate', 'depreciate', 'preciosity'] },
  price: { type: 'root', meaning: '价格', words: ['price', 'priceless', 'pricing', 'pricey'] },
  estim: { type: 'root', meaning: '估价', words: ['estimate', 'estimation', 'estimable', 'underestimate'] },
  med: { type: 'root', meaning: '治疗', words: ['medicine', 'remedy', 'medical', 'medicinal', 'paramedic'] },
  med: { type: 'root', meaning: '中间', words: ['mediate', 'immediate', 'median', 'medium', 'mediocre'] },
  intermedi: { type: 'root', meaning: '中间', words: ['intermediate', 'intermediary', 'intermediate'] },
  civ: { type: 'root', meaning: '公民', words: ['civil', 'civilian', 'civilize', 'civilization', 'civic'] },
  poli: { type: 'root', meaning: '城市', words: ['polite', 'politics', 'metropolis', 'police', 'policy'] },
  polis: { type: 'root', meaning: '城市', words: ['metropolis', 'necropolis', 'cosmopolis'] },
  urb: { type: 'root', meaning: '城市', words: ['urban', 'suburb', 'urbanize', 'interurban', 'exurban'] },
  dom: { type: 'root', meaning: '房屋/统治', words: ['domestic', 'dominate', 'domain', 'dominion', 'domicile'] },
  habit: { type: 'root', meaning: '居住', words: ['habit', 'habitat', 'inhabit', 'cohabit', 'habitable'] },
  habit: { type: 'root', meaning: '习惯', words: ['habit', 'habitual', 'habitude', 'cohabit'] },
  popul: { type: 'root', meaning: '人民', words: ['population', 'popular', 'populate', 'populace', 'populism'] },
  pub: { type: 'root', meaning: '人民', words: ['public', 'publish', 'republic', 'populate', 'populace'] },
  demo: { type: 'root', meaning: '人民', words: ['democracy', 'demographic', 'demonstrate', 'epidemic', 'pandemic'] },
  ethn: { type: 'root', meaning: '种族', words: ['ethnic', 'ethnology', 'ethnocentrism', 'ethnographer'] },
  anthrop: { type: 'root', meaning: '人类', words: ['anthropology', 'anthropoid', 'anthropocentric', 'misanthrope'] },
  lingu: { type: 'root', meaning: '语言', words: ['linguist', 'linguistics', 'bilingual', 'multilingual', 'colloquial'] },
  phil: { type: 'root', meaning: '爱', words: ['philosophy', 'philanthropy', 'philology', 'bibliophile', 'Francophile'] },
  soph: { type: 'root', meaning: '智慧', words: ['philosophy', 'sophist', 'sophisticated', 'sophomore', 'sophism'] },
  soph: { type: 'root', meaning: '聪明', words: ['sophistication', 'sophomore', 'philosophical'] },
  sci: { type: 'root', meaning: '知道', words: ['science', 'conscious', 'subconscious', 'omniscient', 'nescient'] },
  sci: { type: 'root', meaning: '知识', words: ['sciential', 'scientist', 'scientific', 'conscientious'] },
  cogn: { type: 'root', meaning: '知道', words: ['recognize', 'cognizant', 'incognito', 'cognition', 'cognomen'] },
  gnos: { type: 'root', meaning: '知道', words: ['diagnose', 'prognosis', 'agnostic', 'gnosis', 'prognosticate'] },
  log: { type: 'root', meaning: '说/学科', words: ['psychology', 'biology', 'technology', 'dialogue', 'apology'] },
  leg: { type: 'root', meaning: '法律', words: ['legal', 'illegal', 'legitimate', 'legislation', 'legacy'] },
  jur: { type: 'root', meaning: '法律', words: ['jury', 'injure', 'judgment', 'jurist', 'jurisdiction'] },
  jud: { type: 'root', meaning: '判断', words: ['judge', 'judgment', 'judicial', 'prejudice', 'adjudicate'] },
  dict: { type: 'root', meaning: '说', words: ['dictate', 'dictation', 'predict', 'addict', 'indict'] },
  dic: { type: 'root', meaning: '说', words: ['dictate', 'diction', 'dictionary', 'predict', 'contradict'] },
  loqu: { type: 'root', meaning: '说', words: ['eloquent', 'soliloquy', 'colloquial', 'grandiloquent', 'loquacious'] },
  nunc: { type: 'root', meaning: '说', words: ['announce', 'denounce', 'pronounce', 'renounce', 'pronunciation'] },
  claim: { type: 'root', meaning: '叫喊', words: ['claim', 'proclaim', 'exclaim', 'reclaim', 'acclaim'] },
  clam: { type: 'root', meaning: '叫喊', words: ['clamor', 'acclamation', 'exclamation', 'proclamation'] },
  vor: { type: 'root', meaning: '吃', words: ['carnivore', 'herbivore', 'omnivore', 'voracious', 'devour'] },
  vore: { type: 'root', meaning: '吃', words: ['herbivore', 'carnivore', 'omnivore', 'insectivore'] },
  ed: { type: 'root', meaning: '吃', words: ['edible', 'inedible', 'obese', 'esculent'] },
  pot: { type: 'root', meaning: '喝', words: ['potable', 'potation', 'drink', 'beverage'] },
  bib: { type: 'root', meaning: '喝', words: ['bibe', 'imbibe', 'biber', 'bibulous'] },
  dorm: { type: 'root', meaning: '睡', words: ['dormitory', 'dormant', 'dormitive', 'dormancy'] },
  son: { type: 'root', meaning: '声音', words: ['sonic', 'supersonic', 'phonics', 'stereophonic', 'microphone'] },
  son: { type: 'root', meaning: '声音', words: ['resonance', 'consonant', 'dissonance', 'sonnet', 'sonic'] },
  phon: { type: 'root', meaning: '声音', words: ['phonetic', 'phonics', 'telephone', 'symphony', 'euphonious'] },
  lum: { type: 'root', meaning: '光', words: ['luminous', 'illuminate', 'luminary', 'luminescence', 'lumen'] },
  lun: { type: 'root', meaning: '月亮', words: ['lunar', 'lunisolar', 'lunation', 'luniform', 'lune'] },
  sol: { type: 'root', meaning: '太阳', words: ['solar', 'solstice', 'parasol', 'solarize', 'solarium'] },
  helio: { type: 'root', meaning: '太阳', words: ['heliocentric', 'heliosphere', 'heliport', 'heliotrope'] },
  terra: { type: 'root', meaning: '地球', words: ['terrain', 'terrace', 'territory', 'Mediterranean', 'extraterrestrial'] },
  geo: { type: 'root', meaning: '地球', words: ['geography', 'geology', 'geometry', 'geophysics', 'geothermal'] },
  aqu: { type: 'root', meaning: '水', words: ['aquatic', 'aquarium', 'aqueduct', 'subaqueous', 'opaque'] },
  hydra: { type: 'root', meaning: '水', words: ['hydraulic', 'hydroelectric', 'dehydrate', 'hydrangea', 'anhydrous'] },
  aero: { type: 'root', meaning: '空气', words: ['aerobic', 'aerospace', 'aerodynamic', 'aeronautics', 'aerogel'] },
  ign: { type: 'root', meaning: '火', words: ['ignite', 'ignition', 'igneous', 'preignition', 'ignite'] },
  pyr: { type: 'root', meaning: '火', words: ['pyre', 'pyromania', 'antipyretic', 'pyrotechnics', 'empyrean'] },
  pyrol: { type: 'root', meaning: '火', words: ['pyrolysis', 'pyroscope', 'pyrosis', 'pyrotechnic'] },
  therm: { type: 'root', meaning: '热', words: ['thermal', 'thermometer', 'thermodynamics', 'hypothermia', 'thermos'] },
  crystall: { type: 'root', meaning: '晶体', words: ['crystal', 'crystalline', 'crystallize', 'crystallography', 'polycrystalline'] },
  metall: { type: 'root', meaning: '金属', words: ['metal', 'metallurgy', 'metallic', 'metalloid', 'metallurgist'] },
  petr: { type: 'root', meaning: '石头', words: ['petroleum', 'petrify', 'petrography', 'petrology', 'petrochemical'] },
  lith: { type: 'root', meaning: '石头', words: ['lithium', 'lithic', 'neolithic', 'paleolithic', 'lithosphere'] },
  chlor: { type: 'root', meaning: '绿/氯', words: ['chlorophyll', 'chlorine', 'chloride', 'chloroform', 'chlorous'] },
  chrom: { type: 'root', meaning: '颜色', words: ['chrome', 'chromatic', 'chromosome', 'chromatography', 'monochrome'] },
  cyan: { type: 'root', meaning: '蓝绿', words: ['cyanide', 'cyan', 'cyanotic', 'hydrocyanic'] },
  erythr: { type: 'root', meaning: '红', words: ['erythrocyte', 'erythema', 'erythromycin', 'erythrina'] },
  leuc: { type: 'root', meaning: '白', words: ['leucocyte', 'leucoplast', 'leucotomy', 'leucorrhea'] },
  mela: { type: 'root', meaning: '黑', words: ['melanin', 'melancholy', 'melanoma', 'melange', 'melaphyre'] },
  xanth: { type: 'root', meaning: '黄', words: ['xanthic', 'xanthophyll', 'xanthoma', 'xanthate'] },
  vir: { type: 'root', meaning: '毒', words: ['virus', 'virulent', 'virion', 'virology', 'viricide'] },
  path: { type: 'root', meaning: '疾病', words: ['pathology', 'pathogen', 'sympathy', 'antipathy', 'apathy'] },
  path: { type: 'root', meaning: '感受', words: ['empathy', 'sympathy', 'antipathy', 'apathy', 'pathos'] },
  path: { type: 'root', meaning: '疾病', words: ['pathogenic', 'pathogeny', 'pathognomonic'] },
  pharmac: { type: 'root', meaning: '药', words: ['pharmacy', 'pharmacist', 'pharmacology', 'pharmaceutical', 'pharmacopeia'] },
  med: { type: 'root', meaning: '药', words: ['medicine', 'medicinal', 'remedy', 'medication'] },
  cur: { type: 'root', meaning: '关心/治疗', words: ['cure', 'curious', 'secure', 'procure', 'accurate'] },
  san: { type: 'root', meaning: '健康', words: ['sanity', 'sanitary', 'sanitize', 'insane', 'sanatorium'] },
  salub: { type: 'root', meaning: '健康', words: ['salubrious', 'salubrity', 'salutary', 'salute'] },
  vigor: { type: 'root', meaning: '精力', words: ['vigor', 'vigorous', 'invigorate', 'vigorish'] },
  rob: { type: 'root', meaning: '力量', words: ['robust', 'robustness', 'robote', 'robotics'] },
  robust: { type: 'root', meaning: '强壮', words: ['robust', 'robustious', 'robustly'] },
  fort: { type: 'root', meaning: '强', words: ['fort', 'fortress', 'fortify', 'fortitude', 'effort'] },
  firm: { type: 'root', meaning: '坚定', words: ['firm', 'infirm', 'confirm', 'affirm', 'firmness'] },
  stabil: { type: 'root', meaning: '稳定', words: ['stable', 'stability', 'stabilize', 'instability', 'stabilizer'] },
  stant: { type: 'root', meaning: '站立', words: ['stant', 'constant', 'distant', 'instance', 'substance'] },
  sist: { type: 'root', meaning: '站立', words: ['sist', 'resist', 'persist', 'consist', 'insist'] },
  sta: { type: 'root', meaning: '站立', words: ['stay', 'stable', 'status', 'estate', 'obstacle'] },
  stat: { type: 'root', meaning: '站立', words: ['state', 'statue', 'status', 'statute', 'stature'] },
 stitute: { type: 'root', meaning: '站立', words: ['constitute', 'substitute', 'institute', 'prostitute', 'destitute'] },
  struct: { type: 'root', meaning: '建造', words: ['structure', 'construct', 'destroy', 'instruction', 'obstruct'] },
  stru: { type: 'root', meaning: '建造', words: ['structure', 'construct', 'obstruct', 'destroy', 'instrument'] },
  form: { type: 'root', meaning: '形式', words: ['form', 'formal', 'transform', 'reform', 'conform', 'deform'] },
  forma: { type: 'root', meaning: '形式', words: ['formal', 'format', 'formation', 'formula', 'formulate'] },
  morph: { type: 'root', meaning: '形状', words: ['morphology', 'amorphous', 'metamorphosis', 'polymorph', 'anthropomorphic'] },
  fig: { type: 'root', meaning: '形状', words: ['figure', 'figue', 'configuration', 'disfigure'] },
  figur: { type: 'root', meaning: '形状', words: ['figure', 'figurate', 'prefigure', 'transfigure'] },
  image: { type: 'root', meaning: '图像', words: ['image', 'imagine', 'imagination', 'imagery', 'imaging'] },
  mod: { type: 'root', meaning: '模式', words: ['mode', 'model', 'modify', 'moderate', 'modest'] },
  mod: { type: 'root', meaning: '方式', words: ['modulate', 'commodious', 'modish'] },
  typ: { type: 'root', meaning: '类型', words: ['type', 'typical', 'typography', 'prototype', 'stereotype'] },
  styl: { type: 'root', meaning: '风格', words: ['style', 'stylish', 'stylist', 'stylize', 'stylus'] },
  schem: { type: 'root', meaning: '计划', words: ['scheme', 'schematic', 'schematize', 'schema'] },
  plan: { type: 'root', meaning: '计划', words: ['plan', 'plane', 'planar', 'planning', 'planetary'] },
  gram: { type: 'root', meaning: '写/画', words: ['diagram', 'program', 'grammar', 'cryptogram', 'epigram'] },
  mark: { type: 'root', meaning: '标记', words: ['mark', 'marking', 'bookmark', 'landmark', 'hallmark'] },
  sign: { type: 'root', meaning: '标记', words: ['sign', 'signal', 'signify', 'signature', 'signpost'] },
  sign: { type: 'root', meaning: '符号', words: ['sign', 'assign', 'consign', 'design', 'resign'] },
  indic: { type: 'root', meaning: '指示', words: ['indicate', 'indicator', 'indict', 'indiction', 'index'] },
  dic: { type: 'root', meaning: '指示', words: ['indication', 'indicator', 'indices', 'dictionary'] },
  not: { type: 'root', meaning: '知道', words: ['note', 'notice', 'notable', 'notation', 'annotate'] },
  nomin: { type: 'root', meaning: '名字', words: ['nominal', 'nominate', 'denominate', 'ignominious', 'onomancy'] },
  nomin: { type: 'root', meaning: '命名', words: ['nominate', 'nominal', 'cognomen', 'ignominy'] },
  nomin: { type: 'root', meaning: '名称', words: ['noun', 'nomen', 'nomenclature', 'nominate', 'denominate'] },
  onym: { type: 'root', meaning: '名字', words: ['anonymous', 'synonym', 'antonym', 'homonym', 'pseudonym'] },
  nomin: { type: 'root', meaning: '名称', words: ['nomenclature', 'nominal', 'nominate'] },
  verb: { type: 'root', meaning: '词', words: ['verb', 'verbal', 'proverb', 'adverb', 'verbose'] },
  word: { type: 'root', meaning: '词', words: ['word', 'password', 'wordsmith', 'wordplay', 'watchword'] },
  nomin: { type: 'root', meaning: '名称', words: ['nomen', 'nomenclature', 'nominate', 'denominate'] },
  charact: { type: 'root', meaning: '特征', words: ['character', 'characteristic', 'characterize', 'characterization'] },
  idio: { type: 'root', meaning: '个人', words: ['idiom', 'idiosyncrasy', 'idiot', 'idiographic', 'idiolect'] },
  ego: { type: 'root', meaning: '自我', words: ['ego', 'egotism', 'egocentric', 'egoist', 'egomania'] },
  self: { type: 'root', meaning: '自我', words: ['self', 'selfish', 'selfless', 'self-esteem', 'self-aware'] },
  alter: { type: 'root', meaning: '其他', words: ['alter', 'alternate', 'alternative', 'alter ego', 'alteration'] },
  ali: { type: 'root', meaning: '其他', words: ['alias', 'alien', 'alibi', 'alienate', 'alignment'] },
  oth: { type: 'root', meaning: '其他', words: ['other', 'otherwise', 'another', 'otherwise'] },
  mut: { type: 'root', meaning: '改变', words: ['mutate', 'mutation', 'commute', 'immutable', 'mutual'] },
  var: { type: 'root', meaning: '改变', words: ['various', 'variable', 'variety', 'vary', 'invariant'] },
  vari: { type: 'root', meaning: '变化', words: ['variable', 'variety', 'variance', 'variation', 'variant'] },
  nov: { type: 'root', meaning: '新', words: ['novel', 'novelty', 'innovate', 'renovate', 'nova'] },
  neo: { type: 'root', meaning: '新', words: ['neologism', 'neon', 'neoclassic', 'neophyte', 'neoplasm'] },
  cent: { type: 'root', meaning: '百', words: ['century', 'centennial', 'centimeter', 'percent', 'centipede'] },
  mille: { type: 'root', meaning: '千', words: ['millennium', 'millennial', 'millimeter', 'millepore'] },
  mil: { type: 'root', meaning: '千', words: ['mile', 'military', 'militia', 'millenary'] },
  prim: { type: 'root', meaning: '第一', words: ['prime', 'primary', 'primitive', 'primate', 'primeval'] },
  sec: { type: 'root', meaning: '第二', words: ['second', 'secondary', 'secundine', 'secondhand'] },
  tert: { type: 'root', meaning: '第三', words: ['tertiary', 'tertian', 'tertium', 'tertius'] },
  quart: { type: 'root', meaning: '第四', words: ['quart', 'quarter', 'quartan', 'quartet', 'quarto'] },
  quint: { type: 'root', meaning: '第五', words: ['quintet', 'quintuple', 'quintessence', 'quintuplicate'] },
  sex: { type: 'root', meaning: '六', words: ['sextet', 'sextant', 'sexism', 'sexual', 'sexy'] },
  sept: { type: 'root', meaning: '七', words: ['September', 'septet', 'septic', 'septuagenarian'] },
  octo: { type: 'root', meaning: '八', words: ['October', 'octave', 'octopus', 'octagon', 'octet'] },
  non: { type: 'root', meaning: '九', words: ['nonagon', 'ninth', 'nonary', 'novemdecim'] },
  dec: { type: 'root', meaning: '十', words: ['decade', 'December', 'decimal', 'decimate'] },
  hendec: { type: 'root', meaning: '十一', words: ['hendecagon', 'hendecasyllabic'] },
  dodeca: { type: 'root', meaning: '十二', words: ['dodecagon', 'dodecahedron', 'dodecaphonic'] },
  milli: { type: 'root', meaning: '千', words: ['millimeter', 'milligram', 'millennial', 'millennium'] },
  micro: { type: 'root', meaning: '小', words: ['microscope', 'microwave', 'microphone', 'microbiology'] },
  macro: { type: 'root', meaning: '大', words: ['macrocosm', 'macroeconomics', 'macrostructure', 'macrolide'] },
  magn: { type: 'root', meaning: '大', words: ['magnify', 'magnificent', 'magnitude', 'magnate', 'magnolia'] },
  maxi: { type: 'root', meaning: '最大', words: ['maxim', 'maximum', 'maxilla', 'maximize'] },
  mini: { type: 'root', meaning: '小', words: ['minimize', 'minimum', 'minister', 'minor', 'mint'] },
  micr: { type: 'root', meaning: '小', words: ['microscopic', 'microref', 'microfilm'] },
  parv: { type: 'root', meaning: '小', words: ['parvo', 'parvol', 'parvitude', 'parvis'] },
  ampl: { type: 'root', meaning: '大', words: ['ample', 'amplify', 'amplitude', 'amplifier'] },
  grand: { type: 'root', meaning: '大', words: ['grand', 'grandeur', 'grandstand', 'aggrandize'] },
  gigant: { type: 'root', meaning: '巨大', words: ['gigantic', 'giant', 'gigantesque', 'gigantism'] },
  titan: { type: 'root', meaning: '巨大', words: ['titanic', 'titan', 'titanesque', 'titanium'] },
  omn: { type: 'root', meaning: '全', words: ['omnipresent', 'omnipotent', 'omniscient', 'omnivorous'] },
  pant: { type: 'root', meaning: '全', words: ['panorama', 'pandemic', 'pantheon', 'pantheism', 'pantomime'] },
  hol: { type: 'root', meaning: '全', words: ['holistic', 'hologram', 'holocaust', 'holocrine'] },
  tot: { type: 'root', meaning: '全', words: ['total', 'totality', 'totem', 'detonate'] },
  univ: { type: 'root', meaning: '统一', words: ['universe', 'university', 'universal', 'unify'] },
  uni: { type: 'root', meaning: '一', words: ['uniform', 'union', 'unique', 'unite', 'unity'] },
  bin: { type: 'root', meaning: '二', words: ['binary', 'binaural', 'bine', 'binominal'] },
  bi: { type: 'root', meaning: '二', words: ['bicycle', 'bilingual', 'bilateral', 'biennial'] },
  tri: { type: 'root', meaning: '三', words: ['triangle', 'trinity', 'triple', 'tribe', 'tribal'] },
  quadr: { type: 'root', meaning: '四', words: ['quadrant', 'quadruple', 'quadriceps', 'quadrilateral'] },
  tetr: { type: 'root', meaning: '四', words: ['tetrad', 'tetrahedron', 'tetragonal', 'tetrarch'] },
  pent: { type: 'root', meaning: '五', words: ['pentagon', 'pentagram', 'pentathlon', 'pentoxide'] },
  quin: { type: 'root', meaning: '五', words: ['quintet', 'quintuple', 'quintessence', 'quintuplicate'] },
  sex: { type: 'root', meaning: '六', words: ['sextet', 'sexagenarian', 'sextant', 'sexto'] },
  hept: { type: 'root', meaning: '七', words: ['heptagon', 'heptahedron', 'heptameter', 'heptarchy'] },
  oct: { type: 'root', meaning: '八', words: ['octagon', 'octave', 'octopus', 'octogenarian'] },
  enne: { type: 'root', meaning: '九', words: ['enneagon', 'enneahedron', 'ennuple'] },
  dec: { type: 'root', meaning: '十', words: ['decade', 'decagon', 'decahedron', 'decameter'] },
  hendec: { type: 'root', meaning: '十一', words: ['hendecagon', 'hendecasyllable'] },
  dodec: { type: 'root', meaning: '十二', words: ['dodecagon', 'dodecahedron', 'dodecaphony'] },
  vigint: { type: 'root', meaning: '二十', words: ['vigintillion', 'vigintivetial'] },
  cent: { type: 'root', meaning: '百', words: ['century', 'centennial', 'centigrade', 'centipede'] },
  mill: { type: 'root', meaning: '千', words: ['million', 'millennial', 'millimeter', 'millinery'] },
  micr: { type: 'root', meaning: '百万', words: ['microphone', 'microscope', 'microwave', 'microbiology'] },

  // ==================== 后缀 Suffix ====================
  // 名词后缀
  tion: { type: 'suffix', meaning: '名词后缀', words: ['nation', 'action', 'education', 'creation', 'information', 'revolution', 'pollution', 'attention', 'station', 'foundation'] },
  sion: { type: 'suffix', meaning: '名词后缀', words: ['vision', 'division', 'decision', 'television', 'conclusion', 'expansion', 'collision', 'precision', 'version', 'dimension'] },
  ment: { type: 'suffix', meaning: '名词后缀', words: ['development', 'movement', 'treatment', 'government', 'achievement', 'establishment', 'improvement', 'environment', 'investment', 'management'] },
  ness: { type: 'suffix', meaning: '名词后缀', words: ['happiness', 'sadness', 'darkness', 'kindness', 'weakness', 'illness', 'business', 'awareness', 'carelessness', 'loneliness'] },
  ity: { type: 'suffix', meaning: '名词后缀', words: ['activity', 'reality', 'nationality', 'electricity', 'possibility', 'community', 'simplicity', 'regularity', 'maturity', 'complexity'] },
  ty: { type: 'suffix', meaning: '名词后缀', words: ['safety', 'beauty', 'loyalty', 'cruelty', 'novelty', 'poverty', 'plenty', 'society', 'anxiety', 'variety'] },
  er: { type: 'suffix', meaning: '名词后缀(人/物)', words: ['teacher', 'player', 'worker', 'writer', 'reader', 'speaker', 'leader', 'driver', 'singer', 'dancer'] },
  or: { type: 'suffix', meaning: '名词后缀(人/物)', words: ['doctor', 'director', 'actor', 'author', 'editor', 'visitor', 'professor', 'counselor', 'inventor', 'sailor'] },
  ist: { type: 'suffix', meaning: '名词后缀(人/专家)', words: ['artist', 'scientist', 'tourist', 'pianist', 'dentist', 'journalist', 'novelist', 'realist', 'materialist', 'idealist'] },
  ian: { type: 'suffix', meaning: '名词后缀(人)', words: ['musician', 'historian', 'physician', 'technician', 'electrician', 'magician', 'optician', 'politician', 'mathematician', 'astronomian'] },
  ant: { type: 'suffix', meaning: '名词后缀(人)', words: ['student', 'applicant', 'participant', 'assistant', 'assistant', 'immigrant', 'accountant', 'servant', 'defendant', 'merchant'] },
  ent: { type: 'suffix', meaning: '名词后缀(人)', words: ['student', 'president', 'resident', 'agent', 'patient', 'incident', 'evidence', 'confidence', 'continent', 'competent'] },
  ee: { type: 'suffix', meaning: '名词后缀(被动者)', words: ['employee', 'trainee', ' interviewee', 'referee', 'trustee', 'nominee', 'devotee', 'selectee', 'expellee', 'detainee'] },
  ees: { type: 'suffix', meaning: '名词后缀', words: ['refugee', 'guarantee', 'patentee', 'licensee', 'mortgagee'] },
  ure: { type: 'suffix', meaning: '名词后缀', words: ['culture', 'nature', 'structure', 'pressure', 'pleasure', 'measure', 'treasure', 'procedure', 'furniture', 'departure'] },
  ture: { type: 'suffix', meaning: '名词后缀', words: ['future', 'picture', 'mixture', 'adventure', 'fixture', 'signature', 'departure', 'creature', 'capture', 'texture'] },
  sure: { type: 'suffix', meaning: '名词后缀', words: ['measure', 'pleasure', 'treasure', 'closure', 'enclosure', 'composure'] },
  age: { type: 'suffix', meaning: '名词后缀', words: ['storage', 'village', 'marriage', 'postage', 'baggage', 'cottage', 'damage', 'percentage', 'heritage', 'carriage'] },
  al: { type: 'suffix', meaning: '名词后缀', words: ['arrival', 'approval', 'removal', 'recital', 'trial', 'denial', 'refusal', 'proposal', 'reviewal', 'appraisal'] },
  ial: { type: 'suffix', meaning: '名词后缀', words: ['material', 'racial', 'financial', 'initial', 'special', 'official', 'artificial', 'beneficial', 'commercial', 'industrial'] },
  ual: { type: 'suffix', meaning: '名词后缀', words: ['actual', 'visual', 'gradual', 'annual', 'perpetual', 'intellectual', 'conceptual', 'punctual', 'sexual', 'ritual'] },
  ery: { type: 'suffix', meaning: '名词后缀', words: ['slavery', 'drudgery', 'scenery', 'machinery', 'recovery', 'delivery', 'discovery', 'mastery', 'bakery', 'nursery'] },
  ry: { type: 'suffix', meaning: '名词后缀', words: ['family', 'country', 'poetry', 'chemistry', 'history', 'mystery', 'discovery', 'slavery', 'banditry', '凡尔纳'] },
  dom: { type: 'suffix', meaning: '名词后缀(状态/领域)', words: ['freedom', 'kingdom', 'wisdom', 'random', '荒谬', 'christendom', 'earldom', 'radicalism', 'martyrdom'] },
  ship: { type: 'suffix', meaning: '名词后缀(状态/技能)', words: ['friendship', 'leadership', 'membership', 'ownership', 'citizenship', 'scholarship', 'fellowship', 'partnership', 'hardship', 'worship'] },
  hood: { type: 'suffix', meaning: '名词后缀(状态)', words: ['childhood', 'brotherhood', 'sisterhood', 'neighborhood', 'likelihood', 'manhood', 'womanhood', 'priesthood', 'knighthood', 'parenthood'] },
  head: { type: 'suffix', meaning: '名词后缀', words: ['head', 'landscape', 'lead', 'bed', '耳'] },
  cy: { type: 'suffix', meaning: '名词后缀(状态)', words: ['democracy', 'privacy', 'accuracy', 'literacy', 'fluency', 'efficiency', 'frequency', 'urgency', 'tendency', 'currency'] },
  ace: { type: 'suffix', meaning: '名词后缀', words: ['furnace', 'palace', 'space', 'interface', 'workplace', 'birthplace', 'restplace', 'stronghold', 'watermark', 'airship'] },
  ade: { type: 'suffix', meaning: '名词后缀', words: ['decade', 'crusade', 'masquerade', 'cavalcade', 'parade', 'blockade', 'ambuscade', 'cascade', 'rocade'] },
  ism: { type: 'suffix', meaning: '名词后缀(主义)', words: ['capitalism', 'socialism', 'communism', 'nationalism', 'realism', 'idealism', 'materialism', 'optimism', 'pessimism', 'journalism'] },
  logy: { type: 'suffix', meaning: '名词后缀(学科)', words: ['biology', 'psychology', 'technology', 'sociology', 'anthropology', 'archaeology', 'geology', 'ecology', 'terminology', 'methodology'] },
  ology: { type: 'suffix', meaning: '名词后缀(学科)', words: ['psychology', 'biology', 'geology', 'technology', 'archaeology', 'ecology', 'sociology', 'anthropology', 'terminology', 'methodology'] },
  ogr: { type: 'suffix', meaning: '名词后缀(写)', words: ['biography', 'autobiography', 'geography', 'photography', 'cinematography', 'calligraphy', 'lithography', 'stenography', 'choreography', 'demography'] },
  graph: { type: 'suffix', meaning: '名词后缀(写/画)', words: ['photograph', 'telegraph', 'autograph', 'paragraph', 'monograph', 'seismograph', 'spectrograph', 'barograph', 'chronograph', 'xerograph'] },
  scope: { type: 'suffix', meaning: '名词后缀(看)', words: ['telescope', 'microscope', 'stethoscope', 'gyroscope', 'kaleidoscope', 'horoscope', 'periscope', 'oscilloscope', 'spectroscope', 'thermascope'] },
  scope: { type: 'suffix', meaning: '观察仪器', words: ['microscope', 'telescope', 'stethoscope'] },
  phobia: { type: 'suffix', meaning: '名词后缀(恐惧)', words: ['claustrophobia', 'acrophobia', 'arachnophobia', 'hydrophobia', 'xenophobia', 'homophobia', 'agoraphobia', 'nyctophobia', 'photophobia', 'pathophobia'] },

  // 动词后缀
  ize: { type: 'suffix', meaning: '动词后缀(使...)', words: ['realize', 'recognize', 'utilize', 'civilize', 'modernize', 'globalize', 'systemize', 'standardize', 'organize', 'dramatize'] },
  ify: { type: 'suffix', meaning: '动词后缀(使...)', words: ['simplify', 'certify', 'justify', 'identify', 'purify', 'qualify', 'modify', 'signify', 'intensify', 'magnify'] },
  en: { type: 'suffix', meaning: '动词后缀(使...)', words: ['strengthen', 'lengthen', 'widen', 'deepen', 'brighten', 'shorten', 'soften', 'harden', 'quicken', 'loosen'] },
  ize: { type: 'suffix', meaning: '动词化', words: ['modernize', 'organize', 'realize', 'summarize', 'crystallize'] },

  // 形容词后缀
  ful: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['beautiful', 'wonderful', 'careful', 'powerful', 'useful', 'meaningful', 'colorful', 'helpful', 'painful', 'grateful'] },
  less: { type: 'suffix', meaning: '形容词后缀(无...)', words: ['useless', 'careless', 'hopeless', 'meaningless', 'fearless', 'endless', 'harmless', 'helpless', 'restless', 'priceless'] },
  ous: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['dangerous', 'famous', 'generous', 'curious', 'serious', 'obvious', 'various', 'spontaneous', 'courteous', 'gorgeous'] },
  ious: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['anxious', 'conscious', 'delicious', 'precious', 'vicious', 'spacious', 'gracious', 'suspicious', 'ambitious', 'cautious'] },
  eous: { type: 'suffix', meaning: '形容词后缀', words: ['gorgeous', 'courteous', 'erroneous', 'simultaneous', 'spontaneous', 'aneous'] },
  ive: { type: 'suffix', meaning: '形容词后缀(...性的)', words: ['active', 'creative', 'expensive', 'effective', 'native', 'positive', 'negative', 'sensitive', 'relative', 'attractive'] },
  ative: { type: 'suffix', meaning: '形容词后缀', words: ['native', 'representative', 'qualitative', 'authoritative', 'relative', 'legislative', 'administrative', 'competitive', 'constructive', 'protective'] },
  itive: { type: 'suffix', meaning: '形容词后缀', words: ['primitive', 'sensitive', 'positive', 'negative', 'active', 'passive', 'fugitive'] },
  able: { type: 'suffix', meaning: '形容词后缀(可...的)', words: ['comfortable', 'reasonable', 'available', 'valuable', 'remarkable', 'acceptable', 'enjoyable', 'reliable', 'possible', 'probable'] },
  ible: { type: 'suffix', meaning: '形容词后缀(可...的)', words: ['terrible', 'possible', 'visible', 'sensible', 'responsible', 'flexible', 'accessible', 'legible', 'invincible', 'compatible'] },
  al: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['natural', 'personal', 'national', 'cultural', 'central', 'typical', 'final', 'formal', 'real', 'special'] },
  ial: { type: 'suffix', meaning: '形容词后缀', words: ['social', 'racial', 'financial', 'commercial', 'industrial', 'artial', 'beneficial', 'artificial', 'idential'] },
  ual: { type: 'suffix', meaning: '形容词后缀', words: ['actual', 'gradual', 'annual', 'perpetual', 'intellectual', 'habitual', 'ritual', 'sensual', 'conceptual'] },
  ent: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['different', 'present', 'silent', 'patient', 'constant', 'dependent', 'independent', 'excellent', 'violent', 'fluent'] },
  ant: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['important', 'different', 'pleasant', 'distant', 'significant', 'relevant', 'tolerant', 'brilliant', 'elegant', 'radiant'] },
  ary: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['ordinary', 'necessary', 'temporary', 'primary', 'secondary', 'voluntary', 'legendary', 'military', 'ordinary', 'customary'] },
  ory: { type: 'suffix', meaning: '形容词后缀', words: ['satisfying', 'compulsory', 'contradictory', 'directory', 'factory', 'laudatory', 'andatory'] },
  ic: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['basic', 'scientific', 'economic', 'historic', 'musical', 'political', 'physical', 'typical', 'practical', 'theoretical'] },
  ical: { type: 'suffix', meaning: '形容词后缀', words: ['historical', 'political', 'biological', 'grammatical', 'logical', 'critical', 'typical', 'vertical', 'classical', 'technological'] },
  il: { type: 'suffix', meaning: '形容词后缀', words: ['civil', 'legal', 'military', 'artificial', 'commercial', 'financial'] },
  ile: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['mobile', 'docile', 'fragile', 'utile', 'senile', 'juvenile', 'volatile', 'textile', 'automobile', 'reconcile'] },
  oid: { type: 'suffix', meaning: '形容词后缀(像...的)', words: ['humanoid', 'android', 'asteroid', 'celluloid', 'spheroid', 'tabloid', 'mucoid', 'collodion'] },
  like: { type: 'suffix', meaning: '形容词后缀(像...的)', words: ['like', 'dreamlike', 'lifelike', 'worklike', 'home-like', 'childlike', 'businesslike', 'sportlike'] },
  some: { type: 'suffix', meaning: '形容词后缀(...的)', words: ['awesome', 'handsome', 'tiresome', 'bothersome', 'quarrelsome', 'lonesome', 'wholesome', 'troublesome', 'fearsome', 'meddlesome'] },
  ish: { type: 'suffix', meaning: '形容词后缀(像...的)', words: ['selfish', 'childish', 'foolish', 'reddish', 'blackish', 'sweetish', 'spoonful', 'bookish', 'snobbish', 'bearish'] },
  ed: { type: 'suffix', meaning: '形容词后缀(有...的)', words: ['excited', 'interested', 'skilled', 'aged', 'cultured', 'gifted', 'wounded', 'loaned', 'shaped', 'colored'] },
  en: { type: 'suffix', meaning: '形容词后缀(由...制成的)', words: ['wooden', 'golden', 'woolen', 'earthen', 'leaden', 'oaken', 'waxen', 'silken', 'brazen'] },
  ern: { type: 'suffix', meaning: '形容词后缀(方向的)', words: ['northern', 'southern', 'eastern', 'western', 'northeastern', 'southwestern', 'northwestern', 'southeastern'] },
  most: { type: 'suffix', meaning: '形容词后缀(最...)', words: ['utmost', 'innermost', 'outermost', 'lowermost', 'uppermost', 'hindmost', 'foremost', 'aftermost', 'headmost'] },

  // 副词后缀
  ly: { type: 'suffix', meaning: '副词后缀(...地)', words: ['quickly', 'slowly', 'happily', 'carefully', 'beautifully', 'really', 'finally', 'usually', 'especially', 'completely'] },
  ally: { type: 'suffix', meaning: '副词后缀', words: ['basically', 'practically', 'specifically', 'dramatically', 'automatically', 'occasionally', 'absolutely', 'conventionally', 'frantically', 'romantically'] },
  ward: { type: 'suffix', meaning: '副词后缀(向...)', words: ['forward', 'backward', 'upward', 'downward', 'outward', 'inward', 'homeward', 'eastward', 'westward', 'northward'] },
  wards: { type: 'suffix', meaning: '副词后缀', words: ['forwards', 'backwards', 'upwards', 'downwards', 'outwards', 'inwards', 'homewards', 'eastwards', 'westwards'] },
  wise: { type: 'suffix', meaning: '副词后缀(按照...)', words: ['clockwise', 'otherwise', 'likewise', 'sidewise', 'clockwise', 'crosswise', 'endwise', 'lengthwise', 'otherwise'] },
  ways: { type: 'suffix', meaning: '副词后缀', words: ['always', 'anyways', 'anyways', 'sideways', 'crossways', 'lengthways', 'crossways', 'endways'] }
};

// 计算统计
const ROOT_STATS = {
  total: Object.keys(WORD_ROOTS).length,
  prefixes: Object.values(WORD_ROOTS).filter(r => r.type === 'prefix').length,
  roots: Object.values(WORD_ROOTS).filter(r => r.type === 'root').length,
  suffixes: Object.values(WORD_ROOTS).filter(r => r.type === 'suffix').length
};

// 获取用户已学习的词根
function getLearnedRoots() {
  return JSON.parse(localStorage.getItem('memlexis_learned_roots') || '[]');
}

// 保存已学习的词根
function saveLearnedRoot(root) {
  const learned = getLearnedRoots();
  if (!learned.includes(root)) {
    learned.push(root);
    localStorage.setItem('memlexis_learned_roots', JSON.stringify(learned));
  }
}

// 获取词根的学习进度
function getRootProgress() {
  const learned = getLearnedRoots();
  return {
    learned: learned.length,
    total: ROOT_STATS.total,
    percentage: Math.round((learned.length / ROOT_STATS.total) * 100)
  };
}

// 搜索词根
function searchRoots(query) {
  const q = query.toLowerCase();
  return Object.entries(WORD_ROOTS).filter(([key, value]) => {
    return key.toLowerCase().includes(q) ||
           value.meaning.toLowerCase().includes(q) ||
           value.words.some(w => w.toLowerCase().includes(q));
  });
}

// 按类型获取词根
function getRootsByType(type) {
  return Object.entries(WORD_ROOTS).filter(([key, value]) => value.type === type);
}

// 获取词根的关联单词
function getRootWords(rootKey) {
  const root = WORD_ROOTS[rootKey];
  return root ? root.words : [];
}
